quarkus:
  rest:
    jackson:
      optimization:
        enable-reflection-free-serializers: true
    path: /api
  rest-client:
    open-library-api:
      url: https://openlibrary.org
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:file:./mydb-h2
  hibernate-orm:
    schema-management:
      strategy: update

